- name: Установка нужных пакетов
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates
      - curl
    state: present

- name: Добавление GPG ключа
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Добавление docker-репозитория
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Обновление кэша пакетов и установка Docker
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Добавление пользователя в группу Docker
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  when: docker_users | length > 0

- name: Автозапуск сервиса
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
