- name: Install PyMySQL via apt
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: true
  register: apt_task_result
  until: apt_task_result is succeeded
  retries: 10
  delay: 30
