- name: Run WordPress container
  community.docker.docker_container:
    name: "{{ wordpress_container_name }}"
    image: "{{ wordpress_image }}"
    state: started
    restart_policy: always
    env:
      WORDPRESS_DB_HOST: "{{ mysql_container_name }}:3306"
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_database }}"
    networks:
      - name: "{{ docker_network }}"
    ports:
      - "{{ wordpress_port }}"
    volumes:
      - "{{ wordpress_volume }}:/var/www/html"
