all:
  children:
    master:
      hosts:
        master:
          ansible_host: 192.168.135.54
          ansible_user: ubuntu
          ansible_password: pass
          ansible_become_password: pass
    slave:
      hosts:
        slave:
          # Для обучения используется одна VM
          ansible_host: 192.168.135.54
          ansible_user: ubuntu
          ansible_password: pass
          ansible_become_password: pass
    wordpress:
      hosts:
        master:
        slave:
